name = "do-generate"
main = "src/index.ts"
compatibility_date = "2023-12-18"

compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

browser = { binding = "MYBROWSER", type = "browser" }

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" 
new_classes = ["Browser"] 
